build:
  cargo build

build-release:
  cargo build --release

publish:
  cargo publish

run *FLAGS:
  cargo run {{FLAGS}}

test *FLAGS:
  cargo test {{FLAGS}}

testw *FLAGS:
  fd .rs | entr -r cargo test {{FLAGS}}

install:
  cargo install --path .
